apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - url: https://github.com/alaghusundhar/k8s-argocd-deployment
      type: git
    - url: https://github.com/alaghusundhar/metallb-system
      type: git
    - url: https://github.com/alaghusundhar/hello-kubernetes-prod-config
      type: git
