apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - url: https://github.com/s-u-b-h-a-k-a-r-cicd/k8s-argocd-deployment
      type: git
    - url: https://github.com/s-u-b-h-a-k-a-r-cicd/metallb-system
      type: git
    - url: https://github.com/s-u-b-h-a-k-a-r-cicd/hello-kubernetes-prod-config
      type: git
    - url: https://github.com/s-u-b-h-a-k-a-r/go-hello-cloud-code
      type: git
